pipeline:
  build_dry_run:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/crp-loader
    tags:
      - ${DRONE_COMMIT_SHA:0:12}
      - latest
    dry_run: true
    when:
      event: [push, tag]

  build_push:
    image: plugins/docker
    secrets: [ docker_username, docker_password ]
    repo: publicintegrity/crp-loader
    tags:
      - ${DRONE_COMMIT_SHA:0:12}
      - latest
    when:
      event: deployment
      environment: production

  pipeline_update:
    image: publicintegrity/pachctl
    environment:
      - PACHD_ADDRESS=pachd.pachyderm.svc.cluster.local:650
      - IMAGE_TAG=${DRONE_COMMIT_SHA:0:12}
    commands:
      - for file in $(find ./pipelines -name "*.yml"); do yaml2json $file | jq '.transform.image += ":'$${IMAGE_TAG}'"' | pachctl update-pipeline --no-port-forwarding; done
    when:
      event: deployment
      environment: production

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
