pipeline:
  load-campaignfin:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost, cycles ]
    commands:
      - cd ./campaignfin
      - bash load.sh

  load-expend:
    image: publicintegrity/loader
    secrets: [ pgport, pgpassword, pguser, pgdatabase, pghost, cycles ]
    commands:
      - cd ./expend
      - bash load.sh

  slack:
    image: plugins/slack
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
