---
pipeline:
  name: crp-bulk-data-check
transform:
  image: publicintegrity/crp-loader
  cmd:
  - bash
  stdin:
  - ./transforms/check.sh /pfs/out/
parallelism_spec:
  constant: 1
input:
  cron:
    name: tick
    spec: "@daily"
