---
pipeline:
  name: crp-bulk-data-download
transform:
  image: publicintegrity/crp-loader:1393550a6665
  cmd:
  - bash
  stdin:
  - ./transforms/download.sh /pfs/check/ /pfs/out/
parallelism_spec:
  constant: 2
standby: true
input:
  pfs:
    name: check
    repo: crp-bulk-data-check
    glob: /*
    empty_files: true
