---
pipeline:
  name: crp-bulk-data-trim
transform:
  image: publicintegrity/crp-loader:539dc6e069bb
  cmd:
  - bash
  stdin:
  - ./transforms/trim.sh /pfs/unzip/ /pfs/out/
parallelism_spec:
  constant: 2
standby: true
input:
  pfs:
    name: unzip
    repo: crp-bulk-data-unzip
    glob: /*
    lazy: true
