---
pipeline:
  name: crp-bulk-data-unzip
transform:
  image: publicintegrity/crp-loader:1393550a6665
  cmd:
  - bash
  stdin:
  - ./transforms/unzip.sh /pfs/download/ /pfs/out/
parallelism_spec:
  constant: 2
standby: true
input:
  pfs:
    name: download
    repo: crp-bulk-data-download
    glob: /*
