---
pipeline:
  name: crp-bulk-data-unzip
transform:
  image: publicintegrity/crp-loader
  cmd:
  - bash
  stdin:
  - ./transforms/trim.sh /pfs/download/ /pfs/out/
parallelism_spec:
  constant: 2
standby: true
input:
  pfs:
    name: download
    repo: crp-bulk-data-download
    glob: /*
    lazy: true
